apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: taskmaster-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: taskmaster
  replicas: {{ .Values.deployment.replicas }} # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          #image: prodtaskmaster:latest # Image that will be used to containers in the cluster.
          image: "sviswanath57/solarmaster:{{ .Values.deployment.imageVersion}}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

# apiVersion: v1 # Kubernetes API version
# kind: Service # Kubernetes resource kind we are creating
# metadata: # Metadata of the resource kind we are creating
#   name: taskmaster-ssvc
# spec:
#   selector:
#     app: taskmaster
#   ports:
#     - protocol: "TCP"
#       port: 80
#       targetPort: 8080 
#   type: NodePort # type of the service.
---
apiVersion: v1
kind: service
metedata:
    name: taskmaster-ssvc
spec:
   type: NodePort
   ports:
   - targetPort: 80
     protocol: "TCP"
     port: 80
     nodePort: 32000
   selector:
     app: taskmaster
